AllCops:
  NewCops: enable
  Exclude:
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'vendor/bundle/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/wx_customs.rb
    - wx_customs.gemspec

Style/ModuleFunction:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/LineLength:
  Enabled: false
